//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public int IdChicken { get; set; }
        public int IdWorker { get; set; }
        public System.DateTime Date { get; set; }
        public int CountEggs { get; set; }
        public int IdBreed { get; set; }
    
        public virtual Breed Breed { get; set; }
        public virtual Chicken Chicken { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
