//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Chicken
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chicken()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int id { get; set; }
        [DisplayName("Вес")]
        public int Weight { get; set; }
        [DisplayName("Возраст")]
        public int Age { get; set; }
        [DisplayName("Яйца")]
        public int Eggs { get; set; }
        [DisplayName("Номер породы")]
        public int IdBreed { get; set; }
        [DisplayName("Номер цеха")]
        public int IdWorkshop { get; set; }
        [DisplayName("Номер работника")]
        public int IdWorker { get; set; }
    
        public virtual Breed Breed { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual Workshop Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
